app_host: 0.0.0.0
app_name: photonic-ai-system
app_port: 8080
cache:
  cache_ttl_seconds: 3600
  max_memory_mb: 1024
  redis_host: localhost
  redis_password: ''
  redis_port: 6379
  redis_ssl: true
compliance:
  audit_logging: true
  consent_management: true
  data_residency_enforcement: true
  data_retention_days: 2555
  gdpr_compliance: true
  hipaa_compliance: false
  privacy_by_design: true
  sox_compliance: false
database:
  backup_enabled: true
  backup_retention_days: 30
  connection_pool_size: 20
  host: localhost
  name: photonic_ai_prod
  password: ''
  port: 5432
  ssl_enabled: true
  username: photonic_user
debug_mode: false
deployment_timestamp: 2025-08-19 19:08:09 UTC
environment: development
feature_flags:
  adaptive_wavelengths: true
  federated_learning: true
  neural_architecture_search: true
  quantum_enhancement: true
  self_healing: true
global_deployment:
  backup_regions:
  - us-west-1
  - eu-west-2
  cdn_enabled: true
  cdn_provider: cloudflare
  disaster_recovery_enabled: true
  load_balancer_type: application
  multi_region_replication: true
  regions:
  - us-east-1
  - us-west-2
  - eu-west-1
  - ap-southeast-1
  - ap-northeast-1
  - eu-central-1
  - ca-central-1
monitoring:
  alert_email: ops@photonic-ai.com
  grafana_enabled: true
  grafana_port: 3000
  health_check_interval_seconds: 30
  log_level: INFO
  metrics_retention_days: 90
  prometheus_enabled: true
  prometheus_port: 9090
  structured_logging: true
scaling:
  max_instances: 100
  min_instances: 2
  scale_down_cooldown_seconds: 600
  scale_down_threshold: 30.0
  scale_up_cooldown_seconds: 300
  scale_up_threshold: 85.0
  target_cpu_utilization: 70.0
  target_memory_utilization: 80.0
security:
  cors_origins:
  - https://photonic-ai.com
  encryption_algorithm: AES-256-GCM
  https_enabled: false
  jwt_expiration_hours: 24
  jwt_secret_key: ''
  max_requests_per_minute: 1000
  rate_limiting_enabled: true
  ssl_certificate_path: ''
  ssl_private_key_path: ''
testing_mode: false
version: 1.0.0
worker_processes: 4
worker_threads: 8
